mysql:
  image: mysql:5.6.25
  container_name: cosmohome_mysql
  volumes:
   - "./my.cnf:/etc/mysql/conf.d/my.cnf"
   - "cosmohome_mysql:/var/lib/mysql"
  environment: 
   - MYSQL_ROOT_PASSWORD=
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes

cosmohome:
  build: .
  hostname: cosmohome
  links: 
   - mysql
  volumes:
   - "cosmohome_project:/root/projects"
  command: sh -c "./cosmohome_postbuild.py"

apache:
  build: apache
  container_name: cosmohome_apache
  hostname: cosmohome
  links:
   - mysql
  volumes: 
   - "cosmohome_project:/root/projects"
   - "cosmohome_results:/root/results"
  ports: 
   - "80:80"
  tty: true
