version: "3"

volumes:
  mysql:
  project:
  results:

services:
  mysql:
    image: boinc/server_mysql:3.0.0-defaultargs
    network_mode: bridge
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      - BOINC_USER
      - PROJECT

  makeproject:
    build: 
      context: .
      args: 
        - GITTAG
    network_mode: bridge
    links: 
      - mysql
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "./secrets:/run/secrets"
    hostname: makeproject
    environment:
      - URL_BASE
      - PROJECT

  apache:
    build: apache
    hostname: $PROJECT
    network_mode: bridge
    links:
      - mysql
    volumes: 
      - "project:/home/boincadm/project"
      - "results:/results"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./letsencrypt:/etc/letsencrypt"
      - "./secrets:/run/secrets"
      - "/dev/null:/run/secrets/keys/code_sign_private"
    ports: 
      - "80:80"
      - "443:443"
    tty: true
    working_dir: $PROJECT_ROOT
    environment:
      - PROJECT
      - URL_BASE
